### ISSUE TITLE
crash when attempt to sendclienthello without steam connection

### ISSUE THREAD

**Issue by howardchung** [RJacksonm1/node-dota2#105]
Apparently it's possible for node-dota2 to attempt to sendclienthello when its underlying Steam connection is down or otherwise unavailable, which causes a crash.  It should probably handle exceptions.

Trace:
```
2015-09-12T21:26:08.052730+00:00 app[web.1]: /app/node_modules/steam/lib/steam_client.js:124
2015-09-12T21:26:08.052733+00:00 app[web.1]:   this._connection.send(Buffer.concat([header.toBuffer(), body]));
2015-09-12T21:26:08.052734+00:00 app[web.1]:                   ^
2015-09-12T21:26:08.052735+00:00 app[web.1]: TypeError: Cannot read property 'send' of undefined
2015-09-12T21:26:08.032350+00:00 app[web.1]: acct 67 ready, 31/105
2015-09-12T21:26:08.052737+00:00 app[web.1]:     at SteamClient._send (/app/node_modules/steam/lib/steam_client.js:124:19)
2015-09-12T21:26:08.045996+00:00 app[web.1]: acct 9 ready, 33/105
2015-09-12T21:26:08.052738+00:00 app[web.1]:     at SteamClient.send (/app/node_modules/steam/lib/steam_client.js:133:8)
2015-09-12T21:26:08.052739+00:00 app[web.1]:     at SteamGameCoordinator._send (/app/node_modules/steam/lib/handlers/game_coordinator/index.js:49:16)
2015-09-12T21:26:08.082368+00:00 app[web.1]: npm ERR! Linux 3.13.0-61-generic
2015-09-12T21:26:08.052740+00:00 app[web.1]:     at SteamGameCoordinator.send (/app/node_modules/steam/lib/handlers/game_coordinator/index.js:67:8)
2015-09-12T21:26:08.083799+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2015-09-12T21:26:08.083955+00:00 app[web.1]: npm ERR! yasp@3.1.0 start: `node index.js`
2015-09-12T21:26:08.052741+00:00 app[web.1]:     at Dota2Client._sendClientHello [as _onTimeout] (/app/node_modules/dota2/index.js:93:16)
2015-09-12T21:26:08.084089+00:00 app[web.1]: npm ERR! Exit status 1
2015-09-12T21:26:08.052743+00:00 app[web.1]:     at Timer.listOnTimeout (timers.js:119:15)
```

**Comment by howardchung** [comment]
note: I am running a fork of node-dota2 which is synced up with the upstream updates from 1.0.0 branch.

**Comment by howardchung** [comment]
I resolved this by handling Steam disconnections externally.

It's not a breaking issue, more of a decision about whether node-dota2 should handle this case or make the user do it.

**Comment by jimmydorry** [comment]
it sounds like something that would happen every week for up to 30mins. Duly noted that it is not critical.

**Comment by paralin** [comment]
In my case in Dota2 I do monitor the status of the underlying connection and mark the game as closed if Steam goes down.

**Comment by jimmydorry** [comment]
Was a fix applied for handling the exception? At the very least, node-dota2 shouldn't crash from an un-handled exception... unless we document that.

https://github.com/RJacksonm1/node-dota2/issues/102 Issue for README update

**Comment by jimmydorry** [comment]
Kind of out of scope of this dota specific library.

Closed until someone else encounters this behaviour.
