### ISSUE TITLE
configPracticeLobby breaking while handling options

### ISSUE THREAD

**Issue by Apmats** [RJacksonm1/node-dota2#210]
Calling Dota2.configPracticeLobby like this:
```javascript
Dota2.configPracticeLobby(""+Dota2.Lobby.lobby_id, {
                        "server_region": dota2.ServerRegion.EUROPE,
                        });
```

Causes the following error to pop up:

```{r, engine='bash', count_lines}
/somepathhere/node-dota2/handlers/helper.js:72
        type = possibleOptions[option];
                              ^

TypeError: Cannot read property 'server_region' of undefined
    at Object.Dota2._parseOptions (/somepathhere/node-dota2/handlers/helper.js:72:31)
    at Dota2Client.Dota2.Dota2Client.configPracticeLobby (/somepathhere/node-dota2/handlers/lobbies.js:69:25)
    at Dota2Client.<anonymous> (/somepathhere/node-dota2/test/myTest:118:27)
    at emitMany (events.js:108:13)
    at Dota2Client.emit (events.js:182:7)
    at Dota2Client.onChatMessage (/somepathhere/node-dota2/handlers/chat.js:141:10)
    at SteamGameCoordinator.fromGC (/somepathhere/node-dota2/index.js:71:38)
    at emitThree (events.js:97:13)
    at SteamGameCoordinator.emit (events.js:175:7)
    at SteamGameCoordinator.handlers.(anonymous function) (/somepathhere/node-dota2/node_modules/steam/lib/handlers/game_coordinator/index.js:107:10)
```

This is just because in lobbies.js under the Dota2.Dota2Client.prototype.configPracticeLobby definition _parseOptions is called without the Dota2._lobbyOptions argument as the second argument (as it should be and as it is called a few lines above).

I'm submiting a pull request with the simple addition so that this doesn't stump anyone else. :)

**Comment by jimmydorry** [comment]
Are you on dev or master branch. I should have merged dev into master ages ago. :(

**Comment by Apmats** [comment]
Working with dev but it's broken on branches I believe.

**Comment by jimmydorry** [comment]
Ok great. Looking forward to PR.
