### ISSUE TITLE
getMatchMakingStats is broken

### ISSUE THREAD

**Issue by albertcui** [RJacksonm1/node-dota2#243]
```
/home/albert/yasp/node_modules/protobufjs/dist/protobuf.js:2938
                       throw(e);
                       ^

Error: Illegal wire type for field Message.Field .CMsgDOTAMatchmakingStatsResponse.legacy_disabled_groups_source2: 2 (0 expected)
   at Error (native)
   at ProtoBuf.Reflect.FieldPrototype.decode (/home/albert/yasp/node_modules/protobufjs/dist/protobuf.js:3679:23)
   at ProtoBuf.Reflect.MessagePrototype.decode (/home/albert/yasp/node_modules/protobufjs/dist/protobuf.js:3238:45)
   at Function.Message.decode (/home/albert/yasp/node_modules/protobufjs/dist/protobuf.js:2933:37)
   at Dota2Client.onMatchmakingStatsResponse (/home/albert/yasp/node_modules/dota2/handlers/match.js:105:82)
   at SteamGameCoordinator.fromGC (/home/albert/yasp/node_modules/dota2/index.js:71:38)
   at emitThree (events.js:97:13)
   at SteamGameCoordinator.emit (events.js:175:7)
   at SteamGameCoordinator.handlers.(anonymous function) (/home/albert/yasp/node_modules/steam/lib/handlers/game_coordinator/index.js:107:10)
   at SteamGameCoordinator.<anonymous> (/home/albert/yasp/node_modules/steam/lib/handlers/game_coordinator/index.js:19:28)
```

**Comment by howardchung** [comment]
Think we need a proto update

**Comment by jimmydorry** [comment]
Indeed. You can update your local copy by running this (or manually grabbing and dropping those files in the proto directory):

https://github.com/RJacksonm1/node-dota2/blob/master/update_proto.sh

I'm at work, so can't update it easily right now.

**Comment by jimmydorry** [comment]
Old

	message CMsgDOTAMatchmakingStatsResponse {
		optional uint32 matchgroups_version = 1;
		repeated uint32 searching_players_by_group = 2;
		repeated uint32 searching_players_by_group_source2 = 7;
		optional .CMsgMatchmakingGroupServerSample gameserver_sample_source2 = 6;
		optional uint32 legacy_disabled_groups_source2 = 8;
	}

New

	message CMsgDOTAMatchmakingStatsResponse {
		optional uint32 matchgroups_version = 1;
		repeated uint32 legacy_searching_players_by_group_source2 = 7;
		repeated .CMsgMatchmakingMatchGroupInfo match_groups = 8;
	}

**Comment by howardchung** [comment]
And pull request it back

**Comment by jimmydorry** [comment]
Into the dev branch, or just wait like 8 or so hours for me to do it.

**Comment by Crazy-Duck** [comment]
#244

**Comment by jimmydorry** [comment]
Thanks @Crazy-Duck . Some interesting changes.

**Comment by jimmydorry** [comment]
@albertcui use the dev branch. It should work now.

**Comment by howardchung** [comment]
@jimmydorry could you release a new npm package with the new protos?

**Comment by jimmydorry** [comment]
@howardchung Are you compatible with the dev branch? If so I can merge that, and ping rjackson to release.

**Comment by howardchung** [comment]
Looks okay so far. (replays, MMR).  MMstats needs to be deployed (but it's been broken for a month anyway so no one's missing it).  Probably going to let it bake overnight and deploy tomorrow.

**Comment by howardchung** [comment]
You can go ahead and merge/release anyway.  Anyone who's broken can go back to 2.0.0.

**Comment by jimmydorry** [comment]
I actually didn't check the protos in dev. I should probably check that they are the latest. They are certainly more recent than master.

**Comment by howardchung** [comment]
Yeah, you could run the script again and get the latest
