### ISSUE TITLE
On Chat Leave - null pointer exception

### ISSUE THREAD

**Issue by JayFialkowski** [RJacksonm1/node-dota2#291]
The "onChatLeave" event seems to be triggered incorrectly, and the following line of chat.js throws an error:

`if (this.debug) util.log(otherLeft.steam_id + " left channel " + channel.channel_name);`

Stack Trace:

> TypeError: Cannot read property 'channel_name' of undefined
    at Dota2Client.onOtherLeftChannel (/root/node-lobby-bot/node_modules/dota2/handlers/chat.js:205:81)
    at SteamGameCoordinator.fromGC (/root/node-lobby-bot/node_modules/dota2/index.js:57:38)
    at emitThree (events.js:97:13)
    at SteamGameCoordinator.emit (events.js:175:7)
    at SteamGameCoordinator.handlers.(anonymous function) (/root/node-lobby-bot/node_modules/steam/lib/handlers/game_coordinator/index.js:107:10)
    at SteamGameCoordinator.<anonymous> (/root/node-lobby-bot/node_modules/steam/lib/handlers/game_coordinator/index.js:19:28)
    at emitThree (events.js:102:20)
    at SteamClient.emit (events.js:175:7)
    at SteamClient._netMsgReceived (/root/node-lobby-bot/node_modules/steam/lib/steam_client.js:172:10)
    at SteamClient.handlers.(anonymous function) (/root/node-lobby-bot/node_modules/steam/lib/steam_client.js:259:10)

Simple fix:
`if (this.debug && channel) {`

**Comment by jimmydorry** [comment]
Thanks, will look at this shortly.

**Comment by Crazy-Duck** [comment]
It's an old bug, been around since I reworked chat in 2.0.0 I think. Basically it only happens when you didn't properly disconnect the from the GC, after having joined a chat channel. If you reconnect to GC soon after, the GC assumes you're still in the chat (disadvantage of a heartbeat system). So when someone leaves the channel, you still get the events, but as your bot no longer has the channel in cache (cause your bot crashed, you terminated it improperly, ...) it'll throw an error cause it can't find the name of the chat channel. I think the proper way to fix this would be an additional if within the debug block which checks for the channel. If the channel isn't found, it should log with the id from event. That way a log is generated in all cases.

This stays however an edge-case which should theoretically not happen. If you're seeing this error you should probably review the way you're terminating your bot.

**Comment by JayFialkowski** [comment]
Thanks for the quick response. I figured it was a result of a crash not allowing GC/Steam to disconnect correctly.
