### ISSUE TITLE
Bignumber Error

### ISSUE THREAD

**Issue by wiratamadc** [RJacksonm1/node-dota2#59]
11 Mar 14:12:52 - Logged on.
11 Mar 14:12:52 - Launching Dota 2
/Users/wira/dev/node-dota2/node_modules/bignumber.js/bignumber.js:1195
            throw error;
                  ^
BigNumber Error: BigNumber() constructor call without new: 76561198113692125
    at raise (/Users/wira/dev/node-dota2/node_modules/bignumber.js/bignumber.js:1163:25)
    at BigNumber (/Users/wira/dev/node-dota2/node_modules/bignumber.js/bignumber.js:162:29)
    at Dota2Client.ToAccountID (/Users/wira/dev/node-dota2/index.js:61:10)
    at Dota2Client.launch (/Users/wira/dev/node-dota2/index.js:71:25)
    at SteamClient.onSteamLogOn (/Users/wira/dev/node-dota2/test/index.js:16:15)
    at SteamClient.emit (events.js:104:17)
    at SteamClient.handlers.(anonymous function) (/Users/wira/dev/node-dota2/test/node_modules/steam/lib/handlers/user.js:163:10)
    at SteamClient._netMsgReceived (/Users/wira/dev/node-dota2/test/node_modules/steam/lib/steam_client.js:106:26)
    at SteamClient.handlers.(anonymous function) (/Users/wira/dev/node-dota2/test/node_modules/steam/lib/steam_client.js:192:10)
    at SteamClient._netMsgReceived (/Users/wira/dev/node-dota2/test/node_modules/steam/lib/steam_client.js:106:26)

**Comment by kiddick** [comment]
is there any solution?

**Comment by wiratamadc** [comment]
solution is in PR #58 

my bad, I didn't look through before creating the issue thread :(

**Comment by jimmydorry** [comment]
Should be fixed now

**Comment by jimmydorry** [comment]
Please test and confirm here that it works... but I don't see this causing additional errors.

**Comment by wiratamadc** [comment]
it should be fine, if you look at the bignumber.js docs, it all use the 'new' keyword. This is more of library update and therefore should not affecting the code.

**Comment by jimmydorry** [comment]
Yes, I don't expect additional errors... but please report back here after testing.

**Comment by wiratamadc** [comment]
Confirmed this works, no additional errors.

PS: please see PR #50 too.

**Comment by jimmydorry** [comment]
Please keep posts relevant to the thread at hand, and make a new one as required.

I am not touching that PR until it is tested. The tests may depend on the steam package behaving in a certain way.
