### ISSUE TITLE
BigNumber Error

### ISSUE THREAD

**Issue by maximski** [RJacksonm1/node-dota2#60]
I have the following error:

```
BigNumber Error: BigNumber() constructor call without new: 76561198205968656
    at raise (/home/deploy/apps/dotatrace_production/releases/20150311144506/lib/node/dota2_bot/node_modules/dota2/node_modules/bignumber.js/bignumber.js:1163:25)
    at BigNumber (/home/deploy/apps/dotatrace_production/releases/20150311144506/lib/node/dota2_bot/node_modules/dota2/node_modules/bignumber.js/bignumber.js:162:29)
    at Dota2Client.ToAccountID (/home/deploy/apps/dotatrace_production/releases/20150311144506/lib/node/dota2_bot/node_modules/dota2/index.js:61:10)
    at Dota2Client.launch (/home/deploy/apps/dotatrace_production/releases/20150311144506/lib/node/dota2_bot/node_modules/dota2/index.js:71:25)
    at SteamClient.onSteamLogOn (/home/deploy/apps/dotatrace_production/releases/20150311144506/lib/node/dota2_bot/index.js:108:18)
    at SteamClient.emit (events.js:92:17)
    at SteamClient.handlers.(anonymous function) (/home/deploy/apps/dotatrace_production/releases/20150311144506/lib/node/dota2_bot/node_modules/steam/lib/handlers/user.js:159:10)
    at SteamClient._netMsgReceived (/home/deploy/apps/dotatrace_production/releases/20150311144506/lib/node/dota2_bot/node_modules/steam/lib/steam_client.js:102:26)
    at SteamClient.handlers.(anonymous function) (/home/deploy/apps/dotatrace_production/releases/20150311144506/lib/node/dota2_bot/node_modules/steam/lib/steam_client.js:188:10)
    at SteamClient._netMsgReceived (/home/deploy/apps/dotatrace_production/releases/20150311144506/lib/node/dota2_bot/node_modules/steam/lib/steam_client.js:102:26)
    at Connection.emit (events.js:95:17)
    at Connection._readPacket (/home/deploy/apps/dotatrace_production/releases/20150311144506/lib/node/dota2_bot/node_modules/steam/lib/connection.js:50:8)
    at Connection.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Connection.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)
```

So basically the error occurs from dota2/index.js:61:10. I used to fix it by restricting BigNumber.js to 2.0 in my packages, but I think you might want have a look at it for for future development.

**Comment by jimmydorry** [comment]
https://github.com/RJacksonm1/node-dota2/issues/59 

https://github.com/RJacksonm1/node-dota2/pull/58

Should be fixed.
